services:
  - type: web
    name: teammanager
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    startCommand: |
      python manage.py migrate &&
      gunicorn raadaa.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers 2
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: raadaa.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: "teammanager-6ae7.onrender.com,*.onrender.com,*"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
  - type: pserv
    name: teammanager-db
    env: postgres
    plan: free
    region: oregon
    database:
      name: teammanager_db
      databaseName: teammanager
      user: teammanager
