services:
  - type: web
    name: Raadaa
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    startCommand: |
      python manage.py migrate &&
      gunicorn raadaa.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers 2
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: raadaa.settings
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
