"""
Django settings for raadaa project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Define BASE_DIR first
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

dotenv_path = os.path.join(BASE_DIR, '.env')
load_dotenv(dotenv_path)

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'insecure-key-for-dev-only')
FERNET_KEY = os.getenv('FERNET_KEY')
# DEBUG = False
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'
MAIN_DOMAIN = os.getenv('MAIN_DOMAIN', 'http://localhost:8000')
# ALLOWED_HOSTS configuration
# If DJANGO_ALLOWED_HOSTS is a comma-separated string in .env, split it into a list
allowed_hosts_str = os.getenv('DJANGO_ALLOWED_HOSTS')
ALLOWED_HOSTS = (
    allowed_hosts_str.split(',') if allowed_hosts_str
    else [
        MAIN_DOMAIN,
        '.' + MAIN_DOMAIN,
        'raadaa.onrender.com',
        'www.raadaa.onrender.com',
        'localhost',
        '*.localhost',
        '.localhost',
        '127.0.0.1',
        '.teammanager.ng',
        'teammanager.ng',
        'transnet-cloud.localhost',
        'raadaa.localhost',
        'miniago.localhost',
        '13.61.189.68', # Add test host IP
        'steffanie-superchivalrous-reverentially.ngrok-free.dev',
    ]
)

# CSRF_TRUSTED_ORIGINS configuration
# If CSRF_TRUSTED_ORIGINS is a comma-separated string in .env, split it into a list
csrf_trusted_origins_str = os.getenv('CSRF_TRUSTED_ORIGINS')
CSRF_TRUSTED_ORIGINS = (
    csrf_trusted_origins_str.split(',') if csrf_trusted_origins_str
    else [
        'https://teammanager.ng',
        'https://.teammanager.ng',
        'https://raadaa.onrender.com',
        'https://*.onrender.com',
        'http://localhost:8000',
        'http://*.localhost:8000',
        'http://.localhost:8000',
        'http://127.0.0.1:8000',
        'http://transnet-cloud.localhost:8000',
        'http://raadaa.localhost:8000',
        'http://miniago.localhost:8000',
        'http://13.61.189.68:8000',  # Add test host IP
    ]
)

# Temporarily disable CSRF_COOKIE_SECURE for HTTP testing
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False') == 'True'
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False') == 'True'
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'  # Redirect HTTP to HTTPS
# CSRF_COOKIE_SECURE = False
# SESSION_COOKIE_SECURE = False
# SECURE_SSL_REDIRECT = False
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# MEDIA_URL = "/media/"
# MEDIA_ROOT = os.path.join(BASE_DIR, "media")

if DEBUG:
    # Local storage
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
else:
    # S3 storage
    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME")  # e.g. "us-east-1"
    AWS_QUERYSTRING_AUTH = False  # False = public URLs
    AWS_LOCATION = "media"

    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/{AWS_LOCATION}/"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = "home"  # Redirect to dashboard after login
LOGOUT_REDIRECT_URL = "login"  # Redirect to login after logout
# PDFKIT_CONFIG = {
#     'wkhtmltopdf': r"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"
# }
AUTH_USER_MODEL = "documents.CustomUser"

# Zoho mail provider email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.zoho.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""

X_FRAME_OPTIONS = 'SAMEORIGIN'

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
        },
    },
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-e0nt-wx^4!^!r1#rn!*g@6@!bp%q=j2m94o8s105%5+ctbzf*0'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django.contrib.sitemaps',  # SEO: Enable sitemap generation
    'crispy_forms',
    'crispy_bootstrap5',
    'rest_framework',
    'rest_framework.authtoken',
    'documents.apps.DocumentsConfig',
    'tenants',
    'crm',
    'ckeditor',
    'ckeditor_uploader',
    'django_cron',
    'storages',
    'django_countries',
    # 'django_extensions',
    'cities_light',
    'memo',
    'leave',
    'permissions',
    'fund_request',
    'checkin',
    'conference_loan',
    'djmoney',
    # 'django_q',
    'widget_tweaks',
]

# ============================================================================
# SEO CONFIGURATION
# ============================================================================
# Site URL for generating absolute URLs in sitemaps and emails
# Update this to your production domain when deploying
SITE_URL = os.getenv('SITE_URL', 'http://localhost:8000')
SITE_NAME = 'TeamManager'

# SEO Meta defaults
SEO_DEFAULT_TITLE = 'TeamManager - Modern Team Management Solution'
SEO_DEFAULT_DESCRIPTION = (
    'TeamManager helps organizations manage teams, tasks, conferences, '
    'and HR processes efficiently with powerful collaboration tools.'
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'documents.anonymous_user_middleware.AnonymousUserAttributeMiddleware',
    'tenants.middleware.SubscriptionCheckMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tenants.middleware.TenantMiddleware',
    'tenants.middleware.EffectiveContextMiddleware',
    'tenants.middleware.ForcePasswordResetMiddleware',
    'tenants.middleware.TenantNoIndexMiddleware',
    # 'tenants.middleware.MetaEventSetupMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'raadaa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "documents/templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TEMPLATES[0]['OPTIONS']['context_processors'] += [
    'documents.context_processors.notification_bar',
    'documents.context_processors.notification_count',
    'documents.context_processors.new_features_context',
    'documents.kyc_context_processors.kyc_status_context',
]

WSGI_APPLICATION = 'raadaa.wsgi.application'

CRON_CLASSES = [
    "documents.cron.BirthdayNotificationCronJob",
    "documents.cron.EventReminderCronJob",
    'documents.cron.SubscriptionExpirationCronJob',  # Regular reminders (30 days)
    'documents.cron.UrgentSubscriptionExpirationCronJob',  # Urgent reminders (7 days)
    "documents.cron.EngagementNudgeCronJob",
]

SUBSCRIPTION_REMINDER_RUN_AT_TIMES = ['09:00']  # Run daily at 9 AM
URGENT_SUBSCRIPTION_REMINDER_RUN_AT_TIMES = ['09:00', '14:00']  # Run twice daily
SUBSCRIPTION_REMINDER_DAYS_THRESHOLD = 30  # Days before expiration to start sending

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Database
if os.getenv("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.config(
            default=os.getenv("DATABASE_URL"),
            conn_max_age=600
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }

# CKEditor base path
CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/'
# CKEditor upload path
CKEDITOR_UPLOAD_PATH = "Uploads/"
# CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Basic',
    },
    'custom_toolbar': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat'],
            ['FontSize', 'Font', 'TextColor', 'BGColor'],
            ['NumberedList', 'BulletedList', '-', 'Blockquote'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight'],
            ['Link', 'Unlink', 'Image', 'Embed'],
            ['Format', 'Styles'],
            ['Source']
        ],
        'height': 400,
        'width': 'auto',
        'extraPlugins': ','.join([
            'uploadimage',  # upload images
            'embed',        # media embeds
            'autoembed',
        ]),
        'filebrowserUploadUrl': '/ckeditor/upload/',
        'removePlugins': 'stylesheetparser',
    },
}

CKEDITOR_RESTRICT_BY_USER = False  # Allow all users to upload


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Google service account
GOOGLE_SERVICE_ACCOUNT_FILE = os.path.join(BASE_DIR, 'credentials', 'google_service_account.json')
GOOGLE_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'credentials','client_secret.json')
GOOGLE_OAUTH_SCOPES = ['https://www.googleapis.com/auth/calendar.events']
if DEBUG:
    GOOGLE_OAUTH_REDIRECT_URI = 'http://localhost:8000/oauth2callback/'
    os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
else:
    GOOGLE_OAUTH_REDIRECT_URI = 'https://teammanager.ng/oauth2callback/'

# Crispy Forms Settings
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"   # or "bootstrap4" if you're on older templates

CITIES_LIGHT_TRANSLATION_LANGUAGES = ['en']  # You can add more languages
CITIES_LIGHT_INCLUDE_COUNTRIES = None  # Set to None to include ALL countries
CITIES_LIGHT_INCLUDE_CITY_TYPES = [
    'PPL', 'PPLA', 'PPLA2', 'PPLA3', 'PPLA4', 'PPLC', 'PPLF', 'PPLG', 
    'PPLL', 'PPLR', 'PPLS', 'STLMT', 'ADM1', 'ADM2'
]

# Paystack
PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY')
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')
PAYSTACK_CALLBACK_URL = os.getenv('PAYSTACK_CALLBACK_URL')

# YouVerify API Configuration (for KYC/KYB verification)
YOUVERIFY_API_KEY = os.getenv('YOUVERIFY_API_KEY', '')
YOUVERIFY_API_URL = os.getenv('YOUVERIFY_API_URL', 'https://api.youverify.co/v2')
YOUVERIFY_ENABLED = os.getenv('YOUVERIFY_ENABLED', 'False') == 'True'

# Transave API Configuration (for Conference Loan/Financing)
TRANSAVE_API_KEY = os.getenv('TRANSAVE_API_KEY', '')
TRANSAVE_API_URL = os.getenv('TRANSAVE_API_URL', 'https://api.transave.com/v1')
TRANSAVE_SECRET_KEY = os.getenv('TRANSAVE_SECRET_KEY', '')
TRANSAVE_ENABLED = os.getenv('TRANSAVE_ENABLED', 'False') == 'True'

# Celery
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'django://')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'django://')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Lagos'

# Optional – good for emails
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_ROUTES = {
    'raadaa.tasks.conf_bulk_accept_and_notify': {'queue': 'emails'},
}

SILENCED_SYSTEM_CHECKS = ['ckeditor.W001']

WEBAUTHN_RP_ID = "localhost" if DEBUG else "teammanager.ng"
WEBAUTHN_RP_NAME = "TeamManager"
# WEBAUTHN_EXPECTED_ORIGIN = "http://localhost:8000" if DEBUG else "https://teammanager.ng"

# Q_CLUSTER = {
#     'name': 'DjangoORM',
#     'workers': 4,
#     'timeout': 90,
#     'retry': 120,
#     'queue_limit': 50,
#     'bulk': 10,
#     'orm': 'default', 
#     'catch_up': False,
#     'sync': False, 
# }