# Generated by Django 4.2.21 on 2026-04-09 09:53

import conference_loan.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0087_payrollapproval_payrollcolumntemplate_and_more'),
        ('tenants', '0014_subscription_duration_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, help_text='Auto-generated loan reference', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Loan amount requested', max_digits=12)),
                ('currency', models.CharField(default='NGN', help_text='Currency code (NGN, USD, etc.)', max_length=3)),
                ('reason', models.TextField(help_text='Reason for requesting the loan')),
                ('expected_date', models.DateField(help_text='Date when loan is expected/needed')),
                ('conference_description', models.TextField(help_text='Tell us about the conference (audience, expected attendance, etc.)')),
                ('expected_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Expected revenue from the conference', max_digits=12, null=True)),
                ('expected_expenses', models.DecimalField(blank=True, decimal_places=2, help_text='Expected total expenses', max_digits=12, null=True)),
                ('guarantor_name', models.CharField(help_text='Full name of guarantor', max_length=255)),
                ('guarantor_phone', models.CharField(help_text="Guarantor's phone number", max_length=20)),
                ('guarantor_email', models.EmailField(help_text="Guarantor's email address", max_length=254)),
                ('guarantor_address', models.TextField(help_text="Guarantor's residential address")),
                ('guarantor_relationship', models.CharField(help_text='Relationship to applicant', max_length=100)),
                ('guarantor_occupation', models.CharField(blank=True, help_text="Guarantor's occupation", max_length=100, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('submitted_to_transave', 'Submitted to Transave'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('repaying', 'Repaying'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('kyc_verified', models.BooleanField(default=False, help_text="Whether applicant's KYC/KYB is verified")),
                ('kyc_verification_date', models.DateTimeField(blank=True, null=True)),
                ('transave_loan_id', models.CharField(blank=True, help_text='Loan ID from Transave system', max_length=255, null=True)),
                ('transave_response', models.JSONField(blank=True, default=dict, help_text='Response data from Transave API')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Approved loan amount (may differ from requested)', max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate percentage', max_digits=5, null=True)),
                ('repayment_period_months', models.PositiveIntegerField(blank=True, help_text='Repayment period in months', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection', null=True)),
                ('disbursement_date', models.DateTimeField(blank=True, null=True)),
                ('disbursement_reference', models.CharField(blank=True, help_text='Disbursement transaction reference', max_length=255, null=True)),
                ('total_repaid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount repaid so far', max_digits=12)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('next_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When loan was submitted for review', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes (not visible to applicant)', null=True)),
                ('applicant', models.ForeignKey(help_text='User applying for the loan', on_delete=django.db.models.deletion.PROTECT, related_name='conference_loan_applications', to=settings.AUTH_USER_MODEL)),
                ('conference', models.ForeignKey(help_text='Conference this loan is for', on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='documents.conference')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_conference_loans', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant requesting the loan', on_delete=django.db.models.deletion.CASCADE, related_name='conference_loans', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Conference Loan',
                'verbose_name_plural': 'Conference Loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Repayment amount', max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_reference', models.CharField(help_text='Payment transaction reference', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('transave_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transave_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='conference_loan.conferenceloan')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('conference_budget', 'Conference Budget'), ('business_plan', 'Business Plan'), ('financial_statement', 'Financial Statement'), ('guarantor_id', 'Guarantor ID'), ('guarantor_letter', 'Guarantor Letter'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to=conference_loan.models.upload_to_loan_documents)),
                ('original_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='conference_loan.conferenceloan')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comments not visible to applicant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='conference_loan.conferenceloan')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conferenceloan',
            index=models.Index(fields=['tenant', 'status'], name='conference__tenant__3e77ab_idx'),
        ),
        migrations.AddIndex(
            model_name='conferenceloan',
            index=models.Index(fields=['applicant', 'status'], name='conference__applica_8de80e_idx'),
        ),
        migrations.AddIndex(
            model_name='conferenceloan',
            index=models.Index(fields=['conference'], name='conference__confere_a55128_idx'),
        ),
        migrations.AddIndex(
            model_name='conferenceloan',
            index=models.Index(fields=['reference_number'], name='conference__referen_158953_idx'),
        ),
    ]
