# Generated by Django 4.2.21 on 2026-04-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceloan',
            name='guarantor_id',
            field=models.FileField(blank=True, help_text="Guarantor's ID document", null=True, upload_to='loan_documents/guarantor_ids/'),
        ),
        migrations.AddField(
            model_name='conferenceloan',
            name='guarantor_signature',
            field=models.FileField(blank=True, help_text="Guarantor's signature", null=True, upload_to='loan_documents/guarantor_signatures/'),
        ),
        migrations.AlterField(
            model_name='loandocument',
            name='document_type',
            field=models.CharField(choices=[('conference_proposal', 'Conference Proposal'), ('budget', 'Budget/Financial Plan'), ('business_plan', 'Business Plan'), ('cac', 'CAC Document'), ('memart', 'MEMART Document'), ('other', 'Other')], max_length=50),
        ),
    ]
